# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_call:

name: phs_package_checks.yaml

jobs:
   Style:
    uses: ./.github/workflows/phs_style.yaml
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit

   Document:
    needs: [Style]
    uses: ./.github/workflows/phs_document.yaml
    permissions:
      contents: write
      pull-requests: write
    secrets: inherit
   
   R-CMD-check:
    needs: [Style, Document]
    uses: ./.github/workflows/phs_R-CMD-check.yaml
    permissions: 
     contents: read
    secrets: inherit

   test-coverage:
    needs: [R-CMD-check]
    uses: ./.github/workflows/phs_test_coverage.yaml
    permissions: 
      contents: read
    secrets: inherit
