# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_call:
  
name: R-CMD-check.yaml

permissions: 
  contents: read
  
jobs:      
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          # Core environments - always run these, even on draft PRs
          - {os: ubuntu-latest, r: 'release', core: true}
          - {os: windows-latest, r: '4.4.1', core: true} # PHS RStudio Desktop
          - {os: ubuntu-latest, r: '4.4.2', core: true}  # PHS Posit Workbench
          
          # Extended environments - skip on draft PRs only
          - {os: windows-latest, r: 'release', core: false}
          - {os: macos-latest, r: 'release', core: false}
          - {os: windows-latest, r: 'devel', http-user-agent: 'release', core: false}
          - {os: ubuntu-latest, r: 'devel', http-user-agent: 'release', core: false}
          - {os: ubuntu-latest, r: 'oldrel-1', core: false}
          - {os: ubuntu-latest, r: 'oldrel-2', core: false}

    # Skip extended environments on draft PRs
    if: ${{ !github.event.pull_request.draft || matrix.config.core }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:    
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: r-lib/actions/setup-pandoc@bd49c52ffe281809afa6f0fecbf37483c5dd0b93 # v2.11.3

      - uses: r-lib/actions/setup-r@bd49c52ffe281809afa6f0fecbf37483c5dd0b93 # v2.11.3
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@bd49c52ffe281809afa6f0fecbf37483c5dd0b93 # v2.11.3
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@bd49c52ffe281809afa6f0fecbf37483c5dd0b93 # v2.11.3
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
