on:
  workflow_call:

name: R-CMD-check-core.yaml

permissions:
  contents: read

jobs:
  R-CMD-check-linux:
    name: Core R-CMD-check – ubuntu-latest (${{ matrix.r }})
    runs-on: ubuntu-latest
    # Run the job inside a Rocker image
    container:
      image: ${{ (matrix.r == 'release' && 'rocker/verse:latest') || (matrix.r == 'devel' && 'rocker/verse:devel') || format('rocker/verse:{0}', matrix.r) }}
            
    strategy:
      fail-fast: false
      matrix:
        # Just add versions here; mapping happens above
        r:
          - release   # current CRAN release
          - '4.4.2'   # Posit Workbench baseline
          - '4.5.1'   # Posit Workbench baseline
          
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Install git and qpdf
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git gh qpdf
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: r-lib/actions/setup-pandoc@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2.12.0
      - uses: r-lib/actions/setup-r-dependencies@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2.12.0
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@a51a8012b0aab7c32ef9d19bf54da93f3254335e # v2.12.0
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
          
