name: Test Workflows

on:
  push:
    branches: [main]
    paths:
      - '**.yaml'
      - '**.yml'
  pull_request:
    paths:
      - '**.yaml'
      - '**.yml'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  test-with-mock-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Health Scotland Actions repo
        uses: actions/checkout@v4
        
      - name: Setup testing environment
        run: |
          # Create a new subdirectory to serve as the mock R package's root
          mkdir mock-package-test
          cd mock-package-test
          
          # Create the mock R package structure
          mkdir -p R
          mkdir -p man
          mkdir -p tests/testthat
          
          # Create minimal R package files
          cat << EOT > DESCRIPTION
          Package: mockpkg
          Version: 0.1.0
          Title: Mock Package for Testing Workflows
          Description: A minimal package to test GitHub Actions workflows.
          Authors@R: person("Test", "User", email = "test@example.com", role = c("aut", "cre"))
          License: MIT
          Encoding: UTF-8
          Roxygen: list(markdown = TRUE)
          RoxygenNote: 7.2.0
          EOT
          
          cat << EOT > R/add.R
          #' Add two numbers
          #'
          #' @param x A number
          #' @param y A number
          #' @return The sum of x and y
          #' @export
          add <- function(x, y) {
            x + y
          }
          EOT
          
          cat << EOT > tests/testthat/test-add.R
          test_that("addition works", {
            expect_equal(add(2, 2), 4)
          })
          EOT
          
          # Copy the workflows into the mock package
          cp -R ../.github .github
          
      - name: Run phs_package_checks workflow
        uses: ./mock-package-test/.github/workflows/phs_package_checks.yaml
        with:
          limit_parallel: false
