name: Test Workflows

on:
  push:
    branches: [main]
    paths:
      - '**.yaml'
      - '**.yml'
  pull_request:
    paths:
      - '**.yaml'
      - '**.yml'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch, tag or SHA to checkout'
        required: true
        default: 'main'

permissions:
  contents: write
  pull-requests: write
  statuses: write

jobs:
  test-with-mock-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Health Scotland Actions repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || github.event.pull_request.head.ref || github.ref }}
          path: phs-actions-repo # Checkout to a subdirectory

      - name: Create mock R package
        run: |
          mkdir -p mock-package-test/R
          mkdir -p mock-package-test/man
          mkdir -p mock-package-test/tests/testthat
          
          # Create minimal R package files
          cat << EOT > mock-package-test/DESCRIPTION
          Package: mockpkg
          Version: 0.1.0
          Title: Mock Package for Testing Workflows
          Description: A minimal package to test GitHub Actions workflows.
          Authors@R: person("Test", "User", email = "test@example.com", role = c("aut", "cre"))
          License: MIT
          Encoding: UTF-8
          Roxygen: list(markdown = TRUE)
          RoxygenNote: 7.2.0
          EOT
          
          cat << EOT > mock-package-test/R/add.R
          #' Add two numbers
          #'
          #' @param x A number
          #' @param y A number
          #' @return The sum of x and y
          #' @export
          add <- function(x, y) {
            x + y
          }
          EOT
          
          cat << EOT > mock-package-test/tests/testthat/test-add.R
          test_that("addition works", {
            expect_equal(add(2, 2), 4)
          })
          EOT
          
      - name: Copy workflows into mock package
        run: cp -R phs-actions-repo/.github mock-package-test/.github

      - name: Run phs_package_checks workflow
        uses: ./mock-package-test/.github/workflows/phs_package_checks.yaml
        with:
          limit_parallel: false
